version: '3.8'

services:
  web:
    build: .
    image: my_laravel_app:latest
    container_name: web
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - web

  php:
    image: php:7.4-fpm
    container_name: php
    restart: always
    volumes:
      - ./public:/var/www/html
    networks:
      - web

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USERNAME: root
      PMA_PASSWORD: password
    ports:
      - 8080:80
    networks:
      - web

networks:
  web:
    driver: bridge
